### ISSUE TITLE
Make video encoding configurable

### ISSUE THREAD

**Issue by sundowndev** [dreamvo/gilfoyle#16]
After #5, create a configuration for video conversion.

### Example

Here's an example from [owncast](https://github.com/owncast/owncast/blob/master/examples/config-example.yaml) : 

```yaml
hls:
  render_audio: true
  video_renditions:
    - name: low
      videoBitrate: 800
      scaledWidth: 640
      fps: 30
      codec: libx64
    - name: medium
      videoBitrate: 1200
      fps: 30
      codec: h264
    - name: high
      videoBitrate: 1600
      fps: 30
      codec: libx64
```
