### ISSUE TITLE
Use goreleaser to push Docker image

### ISSUE THREAD

**Issue by sundowndev** [dreamvo/gilfoyle#163]
### Summary

Goreleaser have native support for pushing Docker images. We should take advantage of it.

### References

- https://goreleaser.com/customization/docker_manifest/

### Examples

```yaml
dockers:
- image_templates:
  - "dreamvo/gilfoyle:{{ .Version }}-amd64"
  use_buildx: true
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "dreamvo/gilfoyle:{{ .Version }}-arm64"
  use_buildx: true
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64"
docker_manifests:
- name_template: dreamvo/gilfoyle:{{ .Version }}
  image_templates:
  - dreamvo/gilfoyle:{{ .Version }}-amd64
  - dreamvo/gilfoyle:{{ .Version }}-arm64
```
