### ISSUE TITLE
Storage API

### ISSUE THREAD

**Issue by sundowndev** [dreamvo/gilfoyle#28]
Create a common interface to interact with various storage backends.

### Example

```yml
storage:
  # choices: fs, s3, gcs, ipfs...
  kind: fs
  cache_path: string # default to ./tmp, env: CACHE_PATH
  fs:
    data_path: string # default to ./data, env: FS_DATA_PATH
  s3:
    host: string
    access_key_id: string
    secret_access_key: string
    region: string
    bucket: string
    useSSL: bool
  gcs:
    credentials_file: string # env: GCS_CREDENTIALS_FILE
  ipfs:
    gateway: string # default to gateway.ipfs.io, env: IPFS_GATEWAY
```

```go
func main() {
  s, err := storage.New(storage.Filesystem)

  s.Save(ctx, strings.NewReader("(╯°□°）╯︵ ┻━┻"), "test")
}
```

### References

- https://github.com/ulule/gostorages
