### ISSUE TITLE
API access mode

### ISSUE THREAD

**Issue by sundowndev** [dreamvo/gilfoyle#97]
A feature to run the instance in read only mode. That means any resource can be edited through the REST API. This can be useful when all of your instance is public but only your application is allowed to manage resources of the instance. Concerned routes will now have a middleware deciding whether to allow the request or not. If ReadOnly mode & auth are enabled and the request does not contain a "Authorization" header, disallow the request.

### Config example

```yaml
settings:
    access_mode: ReadOnly # values: ReadOnly, ReadWrite, Restricted (default: ReadWrite)
    auth:
        enabled: true
        key: <bearer_token>
```
